// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tour_2040.Data;

#nullable disable

namespace Tour_2040.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Tour_2040.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AnhCCCDUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HangThanhVien")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KenhDen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LanDatGanNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayCapVoucherSinhNhatGanNhat")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("NgayDongYMarketing")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("NhanEmailMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("NhanSMSMarketing")
                        .HasColumnType("bit");

                    b.Property<bool>("NhanZaloMarketing")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLanDatTour")
                        .HasColumnType("int");

                    b.Property<int>("SoLanHuy")
                        .HasColumnType("int");

                    b.Property<string>("SoThichAnUong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoThichLoaiTour")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SoThichMua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoThichMucGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoThichPhuongTien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongChiTieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tour_2040.Models.DanhGiaTour", b =>
                {
                    b.Property<string>("MaDanhGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HinhAnhUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LichTrinhId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<string>("TourId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("LichTrinhId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("DanhGiaTours");
                });

            modelBuilder.Entity("Tour_2040.Models.DiaDiem", b =>
                {
                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDiaDiem");

                    b.Property<bool>("ConSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("ConSuDung");

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DiaChiChiTiet");

                    b.Property<string>("DiaChiDayDu")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasColumnName("DiaChiDayDu");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GooglePlaceId");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("Lng");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenDiaDiem");

                    b.Property<int>("XaPhuongId")
                        .HasColumnType("int")
                        .HasColumnName("XaPhuongId");

                    b.HasKey("MaDiaDiem");

                    b.HasIndex("XaPhuongId");

                    b.ToTable("DiaDiem");
                });

            modelBuilder.Entity("Tour_2040.Models.DichVu", b =>
                {
                    b.Property<string>("MaTenDichVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HieuLucTu")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhAnhUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LoaiDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaDiaDiem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThongTinPhapLy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTenDichVu");

                    b.HasIndex("MaDiaDiem");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("Tour_2040.Models.GiaoDich", b =>
                {
                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AnhCCCDUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChiLienHe")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoTenNguoiDaiDien")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TourId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("GiaoDiches");
                });

            modelBuilder.Entity("Tour_2040.Models.GiaoDichChiTiet", b =>
                {
                    b.Property<string>("MaChiTietGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DichVuId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GiaoDichId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenPhuongTien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChiTietGiaoDich");

                    b.HasIndex("DichVuId");

                    b.HasIndex("GiaoDichId");

                    b.ToTable("GiaoDichChiTiets");
                });

            modelBuilder.Entity("Tour_2040.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GiaoDichId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenHopDong")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TourId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("GiaoDichId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("TourId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("Tour_2040.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomKhach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThaiTour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinh", b =>
                {
                    b.Property<string>("MaLichTrinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChuTrangThai")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiaoDichId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHuy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TenLichTrinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TourId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("GiaoDichId");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("LichTrinhs");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinhChiTiet", b =>
                {
                    b.Property<string>("MaLichTrinhChiTiet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BatDauLuc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DiaDiemBatDauId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaDiemId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Gio")
                        .HasColumnType("time");

                    b.Property<DateTime?>("KetThucLuc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LichTrinhId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiHoatDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NgayThu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaLichTrinhChiTiet");

                    b.HasIndex("DiaDiemBatDauId");

                    b.HasIndex("DiaDiemId");

                    b.HasIndex("LichTrinhId");

                    b.ToTable("LichTrinhChiTiets");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinhChiTietDichVu", b =>
                {
                    b.Property<int>("MaLichTrinhChiTietDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinhChiTietDichVu"));

                    b.Property<string>("DichVuId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LichTrinhChiTietId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichTrinhChiTietDichVu");

                    b.HasIndex("DichVuId");

                    b.HasIndex("LichTrinhChiTietId");

                    b.ToTable("LichTrinhChiTietDichVus");
                });

            modelBuilder.Entity("Tour_2040.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ConLamViec")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("Tour_2040.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GiaoDichId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("GiaoDichId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("Tour_2040.Models.TinNhanHoTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LaNhanVien")
                        .HasColumnType("bit");

                    b.Property<string>("MaYeuCauHoTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiGui")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaYeuCauHoTro");

                    b.ToTable("TinNhanHoTros");
                });

            modelBuilder.Entity("Tour_2040.Models.TinhThanh", b =>
                {
                    b.Property<int>("MaTinhThanh")
                        .HasColumnType("int")
                        .HasColumnName("MaTinh");

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTinhThanh");

                    b.ToTable("TinhThanh");
                });

            modelBuilder.Entity("Tour_2040.Models.Tour", b =>
                {
                    b.Property<string>("MaTour")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaDiemChinhId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaTour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhTourUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("bit");

                    b.Property<string>("LichTrinhJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiTour")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("NgayDi")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("NgayVe")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("NoiKhoiHanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NoiKhoiHanhDiaDiemId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoNguoiHienTai")
                        .HasColumnType("int");

                    b.Property<int?>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("YeuCauKhac")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("YeuCauKhachSan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("YeuCauNhaHang")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("YeuCauPhuongTien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("YeuCauVuiChoi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaTour");

                    b.HasIndex("DiaDiemChinhId");

                    b.HasIndex("NoiKhoiHanhDiaDiemId");

                    b.HasIndex("UserId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Tour_2040.Models.TourDichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<string>("DichVuId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DonGiaHienTai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NgayThu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TourId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDichVu");

                    b.HasIndex("DichVuId");

                    b.HasIndex("TourId");

                    b.ToTable("TourDichVus");
                });

            modelBuilder.Entity("Tour_2040.Models.TourLichTrinhNgay", b =>
                {
                    b.Property<string>("MaTourLichTrinhNgay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NgayThu")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TourId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTourLichTrinhNgay");

                    b.HasIndex("TourId");

                    b.ToTable("TourLichTrinhNgay");
                });

            modelBuilder.Entity("Tour_2040.Models.UserVoucher", b =>
                {
                    b.Property<string>("MaUserVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayLuu")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VoucherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaUserVoucher");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("Tour_2040.Models.Voucher", b =>
                {
                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DaSuDung")
                        .HasColumnType("int");

                    b.Property<decimal?>("DonHangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoTienGiamToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThaiDuyet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVoucher");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Tour_2040.Models.XaPhuong", b =>
                {
                    b.Property<int>("MaXaPhuong")
                        .HasColumnType("int")
                        .HasColumnName("MaXaPhuong");

                    b.Property<string>("TenXaPhuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenXaPhuong");

                    b.Property<int>("TinhThanhId")
                        .HasColumnType("int");

                    b.HasKey("MaXaPhuong");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("XaPhuong");
                });

            modelBuilder.Entity("Tour_2040.Models.YeuCauHoTro", b =>
                {
                    b.Property<string>("MaYeuCauHoTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiHoTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraLoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaYeuCauHoTro");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("MaGiaoDich");

                    b.HasIndex("UserId");

                    b.ToTable("YeuCauHoTros");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tour_2040.Models.DanhGiaTour", b =>
                {
                    b.HasOne("Tour_2040.Models.LichTrinh", "LichTrinh")
                        .WithMany("DanhGiaTours")
                        .HasForeignKey("LichTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichTrinh");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.DiaDiem", b =>
                {
                    b.HasOne("Tour_2040.Models.XaPhuong", "XaPhuong")
                        .WithMany("DiaDiems")
                        .HasForeignKey("XaPhuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("Tour_2040.Models.DichVu", b =>
                {
                    b.HasOne("Tour_2040.Models.DiaDiem", "DiaDiem")
                        .WithMany("DichVus")
                        .HasForeignKey("MaDiaDiem");

                    b.Navigation("DiaDiem");
                });

            modelBuilder.Entity("Tour_2040.Models.GiaoDich", b =>
                {
                    b.HasOne("Tour_2040.Models.KhachHang", "KhachHang")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("TourId");

                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.GiaoDichChiTiet", b =>
                {
                    b.HasOne("Tour_2040.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tour_2040.Models.GiaoDich", "GiaoDich")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("GiaoDichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("Tour_2040.Models.HopDong", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany("HopDongs")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Tour_2040.Models.GiaoDich", "GiaoDich")
                        .WithMany("HopDongs")
                        .HasForeignKey("GiaoDichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.KhachHang", "KhachHang")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany("HopDongs")
                        .HasForeignKey("TourId");

                    b.Navigation("GiaoDich");

                    b.Navigation("KhachHang");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinh", b =>
                {
                    b.HasOne("Tour_2040.Models.GiaoDich", "GiaoDich")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("GiaoDichId");

                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("GiaoDich");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinhChiTiet", b =>
                {
                    b.HasOne("Tour_2040.Models.DiaDiem", "DiaDiemBatDau")
                        .WithMany()
                        .HasForeignKey("DiaDiemBatDauId");

                    b.HasOne("Tour_2040.Models.DiaDiem", "DiaDiem")
                        .WithMany()
                        .HasForeignKey("DiaDiemId");

                    b.HasOne("Tour_2040.Models.LichTrinh", "LichTrinh")
                        .WithMany("LichTrinhChiTiets")
                        .HasForeignKey("LichTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("DiaDiemBatDau");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinhChiTietDichVu", b =>
                {
                    b.HasOne("Tour_2040.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.LichTrinhChiTiet", "LichTrinhChiTiet")
                        .WithMany("DichVuKemTheo")
                        .HasForeignKey("LichTrinhChiTietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("LichTrinhChiTiet");
                });

            modelBuilder.Entity("Tour_2040.Models.NhanVien", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.ThanhToan", b =>
                {
                    b.HasOne("Tour_2040.Models.GiaoDich", "GiaoDich")
                        .WithMany("ThanhToans")
                        .HasForeignKey("GiaoDichId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.KhachHang", "KhachHang")
                        .WithMany("ThanhToans")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GiaoDich");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Tour_2040.Models.TinNhanHoTro", b =>
                {
                    b.HasOne("Tour_2040.Models.YeuCauHoTro", "YeuCauHoTro")
                        .WithMany("TinNhanHoTros")
                        .HasForeignKey("MaYeuCauHoTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YeuCauHoTro");
                });

            modelBuilder.Entity("Tour_2040.Models.Tour", b =>
                {
                    b.HasOne("Tour_2040.Models.DiaDiem", "DiaDiemChinh")
                        .WithMany()
                        .HasForeignKey("DiaDiemChinhId");

                    b.HasOne("Tour_2040.Models.DiaDiem", "NoiKhoiHanhDiaDiem")
                        .WithMany()
                        .HasForeignKey("NoiKhoiHanhDiaDiemId");

                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DiaDiemChinh");

                    b.Navigation("NoiKhoiHanhDiaDiem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.TourDichVu", b =>
                {
                    b.HasOne("Tour_2040.Models.DichVu", "DichVu")
                        .WithMany("TourDichVus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany("TourDichVus")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tour_2040.Models.TourLichTrinhNgay", b =>
                {
                    b.HasOne("Tour_2040.Models.Tour", "Tour")
                        .WithMany("TourLichTrinhNgays")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Tour_2040.Models.UserVoucher", b =>
                {
                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tour_2040.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Tour_2040.Models.XaPhuong", b =>
                {
                    b.HasOne("Tour_2040.Models.TinhThanh", "TinhThanh")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("TinhThanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("Tour_2040.Models.YeuCauHoTro", b =>
                {
                    b.HasOne("Tour_2040.Models.KhachHang", "KhachHang")
                        .WithMany("YeuCauHoTros")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tour_2040.Models.GiaoDich", "GiaoDich")
                        .WithMany("YeuCauHoTros")
                        .HasForeignKey("MaGiaoDich");

                    b.HasOne("Tour_2040.Models.ApplicationUser", "User")
                        .WithMany("YeuCauHoTros")
                        .HasForeignKey("UserId");

                    b.Navigation("GiaoDich");

                    b.Navigation("KhachHang");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tour_2040.Models.ApplicationUser", b =>
                {
                    b.Navigation("GiaoDiches");

                    b.Navigation("HopDongs");

                    b.Navigation("YeuCauHoTros");
                });

            modelBuilder.Entity("Tour_2040.Models.DiaDiem", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("Tour_2040.Models.DichVu", b =>
                {
                    b.Navigation("TourDichVus");
                });

            modelBuilder.Entity("Tour_2040.Models.GiaoDich", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("HopDongs");

                    b.Navigation("LichTrinhs");

                    b.Navigation("ThanhToans");

                    b.Navigation("YeuCauHoTros");
                });

            modelBuilder.Entity("Tour_2040.Models.KhachHang", b =>
                {
                    b.Navigation("GiaoDiches");

                    b.Navigation("HopDongs");

                    b.Navigation("ThanhToans");

                    b.Navigation("YeuCauHoTros");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinh", b =>
                {
                    b.Navigation("DanhGiaTours");

                    b.Navigation("LichTrinhChiTiets");
                });

            modelBuilder.Entity("Tour_2040.Models.LichTrinhChiTiet", b =>
                {
                    b.Navigation("DichVuKemTheo");
                });

            modelBuilder.Entity("Tour_2040.Models.TinhThanh", b =>
                {
                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("Tour_2040.Models.Tour", b =>
                {
                    b.Navigation("GiaoDiches");

                    b.Navigation("HopDongs");

                    b.Navigation("TourDichVus");

                    b.Navigation("TourLichTrinhNgays");
                });

            modelBuilder.Entity("Tour_2040.Models.XaPhuong", b =>
                {
                    b.Navigation("DiaDiems");
                });

            modelBuilder.Entity("Tour_2040.Models.YeuCauHoTro", b =>
                {
                    b.Navigation("TinNhanHoTros");
                });
#pragma warning restore 612, 618
        }
    }
}
